#!/bin/bash

set -e

# Set working directory
cd /var/www

mkdir -p /var/share/html
rm -rf /var/share/html/*
cp -r /var/www/public* /var/share/html
chown www:www /var/share/html

# Copy environment file
cp /var/www/.env.example /var/www/.env

# Generate app key
php artisan key:generate

exec "$@"
