name: Build Laravel application using Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mukolla/nginx-php-laravel-mysql
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://65.109.224.101:9000/api/endpoints/2/docker/images/create?fromImage=mukolla%2Fnginx-php-laravel-mysql:latest'
          method: 'POST'
          customHeaders: '{"X-API-Key": "${{ secrets.PORTAINER_TOKEN }}"}'
